### ISSUE TITLE
How to initialize prev_teta.txt ?

### ISSUE THREAD

**Issue by joshimosh** [NNaert/Python-controlled-Braccio-robot-arm#1]
Hello and thank you for your Braccio control software.
I am trying to use your software without camera but rather by supplying the coordinates generated by a Python program.
For test purposes I have written a small program to enter coordinates via keyboard input, but without success so far.
When calling go_to_coordinates, I always get an exception that opening prev_teta.txt fails because it is missing.

How do I provide an initial prev_teta.txt ? I have not found a hint in the sources, but perhaps I can ask you for some 
guidance ?

Update: I have created prev_teta.txt and entered the uncalibrated values "by hand". It seems to work.
The next question be hhow to do calibration ? 
In your video, the quite dramatic improvement of a calibration can be seen. But there is now hint how to calibrate.
Please enlighten me :-)

Thanks a lot in advance.
Regards
Martin

**Comment by NNaert** [comment]
Hi Martin,

The "prev_teta.txt" file is just a way to save the previously calculated angles of the servos. Normally it should create the file on the first run of the program. I should have programmed it that way...  

For the calibration, it's quite simple. 

1.  set all the calibration values to 0 (so that there is no compensation done)
2. write '90' to a certain servo.
3. If the linkage is correctly in line with the previous linkage, no compensation is needed. 
 If this is not the case, add one and write it (90+1) to the servo. Keep doing this until the linkages are in line.
4. example: You will end up with a value of 94. The compensation for that servo is thus 4 (94-90).

I hope this is clear for you. 

Kr,
Natan

**Comment by joshimosh** [comment]
Hi Natan,
thank you, now it is perfectly clear :-)

Cheers
Martin
